[package]
name = "aes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
block-modes = "0.9.1"
hex = "0.4.3"
itertools = "0.12.0"
rand = "0.8.5"



